### ISSUE TITLE
Load XIB into view rather than programmatically.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [muukii/StackScrollView#3]
Since it is already mentioned in `TODO:`  for XIB.

I hope this feature released as early as possible.

**Comment by muukii** [comment]
@Rashesh-Bosamiya 

Thank you.
Okay, I'll try to implement this feature.

**Comment by muukii** [comment]
@Rashesh-Bosamiya 
But, You can use views from XIB currently.

1. create view from XIB
2. append created view to `StackScrollView.append(view: UIView)`

**Comment by muukii** [comment]
@Rashesh-Bosamiya 
Anyway, I've created PR.
https://github.com/muukii/StackScrollView/pull/4

**Comment by muukii** [comment]
@Rashesh-Bosamiya 
#4 has merged.
Please tell me, if you have some idea.
